wordpress:
  build: .
  dockerfile: docker/development/wordpress/Dockerfile
  ports:
    - "80:80"
    - "443:443"
    - "9000:9000"
  links:
    - mysql
  volumes:
    - ./www:/var/www
    - ./logs:/var/log/supervisor

mysql:
  image: mysql:5.6
  ports:
    - "3306:3306"
  entrypoint: /localdb-run.sh
  environment:
    MYSQL_ROOT_PASSWORD: password
  volumes:
  - ./.mysqldata:/var/lib/mysql
  - ./localdb-run.sh:/localdb-run.sh